@localhost = http://127.0.0.1:8000/api

# GET all todos
GET {{localhost}}/todo HTTP/1.1

###
# Get one todo from id
GET {{localhost}}/todo/3 HTTP/1.1

###
# Post todo
POST {{localhost}}/todo/ HTTP/1.1
content-type: application/json

{
   "title": "uhhh",
   "description": " :)",
   "completed": true
}

###
# Modify todo
PUT {{localhost}}/todo/4/ HTTP/1.1
content-type: application/json

{
  "title": "Dev",
  "description": "Code baby !",
  "completed": true
}

###
# Delete one todo from id
DELETE  {{localhost}}/todo/5/ HTTP/1.1